### ISSUE TITLE
[BOGGLE] 탐색할 수 있는 후보 글자가 여러 개일 때 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by dakyommii** [Scaachan/Advanced-Algorithm-Study#13]
BOGGLE 풀이 과정에서 함수를 활용하지 않아 코드가 더 복잡해졌습니다.

일단 함수를 활용하면 
```cpp
if (boggle[a--][b] == find[i][j]) { //다음 일치하는 글자 -> 현위치 위에 있을 경우
	a--;
	result[i] = "YES";
}
else if (boggle[a++][b] == find[i][j]) { //아래에 있을 경우
	a++;
	result[i] = "YES";
}
else if (boggle[a][b--] == find[i][j]) { //좌에 있을 경우
	b--;
	result[i] = "YES";
}
else if (boggle[a][b++] == find[i][j]) { //우에 있을 경우
	b++;
	result[i] = "YES";
}
else if (boggle[a--][b++] == find[i][j]) { //우상향 대각선에 있을 경우
	a--;
	b++;
	result[i] = "YES";
}
else if (boggle[a++][b++] == find[i][j]) { //우하향 대각선에 있을 경우
	a++;
	b++;
	result[i] = "YES";
}
else if (boggle[a++][b--] == find[i][j]) { //좌하향 대각선에 있을 경우
	a++;
	b--;
	result[i] = "YES";
}
else if (boggle[a--][b--] == find[i][j]) { //좌상향 대각선에 있을 경우
	a--;
	b--;
	result[i] = "YES";
}
else if (j == strlen(find[i]) - 1) { //마지막 글자까지 검사 성공
	result[i] = "YES";
}
//중간에 찾는 글자가 보글에 없을 경우 처리 필요
```
상단의 조건문으로 처리한 부분을 간결하게 처리할 수 있을 것 같습니다.

그리고 오류를 처리하다보니 한글자한글자 검사할 때마다 `"YES"`, `"NO"`를 부여했는데, 이 부분의 수정이 필요해 보이고
 
코드가 구조적인 것 같지 않아 전체적으로 풀이방법을 다듬으려 합니다.

## 질문
이 방법으로 풀이를 진행하면 다음으로 갈 수 있는 방법이 여러 개일 경우 오류가 날 것 같습니다.

예를 들어 `P`에서 `R`을 찾는데 `R`이 여러개 있을 경우나,
예제의 경우는 그렇지 않지만 `PANDORA`에서 `P`를 찾는데 보글에 `P`가 여러 개 있을 경우

어느 `P`에서 검사를 시작하느냐에 따라 결과가 달라질 수 있기 때문에, 그 부분에 대한 처리는 안하고 넘어가도 되는지 의문입니다.

**Comment by Scaachan** [comment]
말씀하신대로 보글판에 `P`가 여러군데 있을 수 있습니다. 그 부분을 다 고려해서 코드를 작성하셔야 하고요.

그런데 이 문제는 정말 전형적인 dp 문제라서, 푸는 요령이 따로 있습니다. 

우선 보글판에서 단어를 찾아가는 과정을 단계별로 적정히 나누어보세요.

***
1. 보글판에서 단어의 첫글자와 일치하는 지점을 찾는다.
2. 해당 지점에서 dfs를 이용하여 두번째 글자부터 탐색한다. 
***
1번을 대략 설계하시면 이런 모습으로 될 거에요.
```
for(y : 0 ~ 보글판 세로 끝) {
    for(x : 0 ~ 보글판 가로 끝) {
        if(보글판[y][x] == 단어첫글자)
            if(dfs()) 탐색 종료하고 YES 출력하기;
    }
}
NO 출력하기;
```
그럼 보글판에 `P`가 여러개 있어도 전체를 for문으로 탐색하니 상관 없겠죠 :)

다음 글자인 `R`이 여러 군데 있을 경우는 2번 설계할 때 해결하셔야 합니다.

```
R R R
R P R
R R R
```
만약 1에서 `P`의 지점을 찾았고 해당 지점에서 `dfs()`를 호출했는데, `P` 주변이 이렇다면? 네.. 일단은 저 8방향 모두가 탐색 대상입니다.

그래서 하나의 `R`을 선택했을때 꽝나면, 다시 `P` 지점으로 되돌아가 다른 방향의 `R`을 마저 탐색해야 합니다.

그런데 어떻게 되돌아가는지 궁금하셨던 것 같네요.

물론 구현 방법은 다양합니다만, 가장 대표적으로는 **재귀 함수**를 이용합니다.

두번째부터 마지막 글자 탐색까지는 똑같이 주변 8방향 검사해서 이동하고 또 거기서 8방향 검사하고.. 반복의 연속이므로

아예 `8방향 검사 -> 이동`이라는 반복되는 부분을 하나의 함수로 묶어서 재귀시키면 전체 문제를 간단한 코드로 해결할 수 있습니다.

하지만 1번과 2번으로도 AC가 나오진 않는데, 그건 코드가 아직 최적화되지 않아서 그렇습니다.

지금까진 재귀를 이용한 완전탐색을 구현한 것이지, dp는 아니거든요.

```
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A A A
A A A A A A A A B B
A A A A A A A A B C
```
예시로 이 케이스에서 `AAAAAAAAAC` 를 완전탐색하면 저 무수한 A밭을 돌아다니느라 시간 다 갑니다.

그래서 이미 한번 탐색한 곳이면 또 탐색 안하게끔 차단해주는 기법이 있는데 그게 메모이제이션이고,

2번까지 완성하신 코드에 메모이제이션 살짝 얹으면 그때 dp 풀이가 완성됩니다 ^^

일단은 재귀함수로 완전탐색 구현하는 것까지 공부해보세요.

메모이제이션은 이론 한 번 이해하면 정작 구현은 간단하니 차후 연습하셔도 될 것 같습니다.
