### ISSUE TITLE
[BOGGLE] 중복 알파벳이 있을 경우의 break 처리

### ISSUE THREAD

**Issue by yujungee** [Scaachan/Advanced-Algorithm-Study#15]
### 질문
boggle game board 위에 중복 알파벳이 있을 때는 어떻게 처리해야 할지 궁금합니다.
 (앞에서 break 걸렸지만 뒤에 문자를 발견 할 수 있는 경우)

한 문자에서 여러 방향으로 갈 때는 중복 문자가 있어도 DFS를 사용하면 될 것 같다고 생각하는데, 
시작 문자는 일치하지만 중간에 break 되면 남은 보드판의 문자들이 다시 기회를 갖도록 추가하는 방법은 어떻게 구현해야할까요? break하지 말고 그 안에서  다시 반복문을 통해 확인해야 할까요?

(실력이 미흡해서 죄송합니다😭)

**Comment by Scaachan** [comment]
Duplicate of #13
