### ISSUE TITLE
[CLOCKSYNC] 스위치를 누르는 우선순위를 설정하는 기준이 무엇인가요?

### ISSUE THREAD

**Issue by dakyommii** [Scaachan/Advanced-Algorithm-Study#35]
***
- Related to :  #31 
***
다음 코드에서 `solve_switch_order`은 누를 수 밖에 없는 스위치 순서, `solve_clock_order`은 누를 수 밖에 없는 스위치와 연관된 시계 번호, `check_order`은 나머지 시계 번호입니다.
```
int solve_clock_order[10] = {8,11,13,6,10,7,4,1,3,14};
int solve_switch_order[10] = {4,1,9,3,2,7,8,0,6,5};
int check_order[6] = {0,2,5,9,12,15};
```
스위치에 등장하는 횟수로 시계를 분류하고 각 시계가 연관된 스위치를 괄호에 표기하면

1️⃣ 8(4), 11(1), 12(4), 13(9)
2️⃣ 1(0, 8), 6(3, 4), 9(1, 9), 10(2, 4)
3️⃣ 0(0, 3, 5), 2(0, 5, 8)
4️⃣ 3(1, 6, 8, 9), 5(3, 7, 8, 9), 7(1, 3, 4, 7), 14(2, 5, 6, 7), 15(2, 5, 6, 7)
5️⃣ 4(2, 3, 7, 8, 9)

이렇게 표기할 수 있습니다.

여기서 4, 1, 9는 8, 11, 12, 13이 등장하는 유일한 스위치이기 때문에 누를 수밖에 없는 스위치가 되고 유일한 스위치를 갖는 8 ,11, 13이 스위치와 연관된 시계 번호가 됩니다. 이어서 2번 등장하는 시계를 보면 이미 누른 4번 스위치를 제외하면 6, 10시계도 유일한 스위치를 가지므로 6, 10 시계는 누를 수 밖에 없는 스위치와 연관된 시계 번호가 되고 6, 10 시계를 갖는 3, 2번 스위치도 누를 수 밖에 없는 스위치가 됩니다. 
그런데 나머지 스위치들은(4,1,9,3,2를 제외한 나머지 스위치) 어떤 기준으로 우선순위를 설정하는지 모르겠습니다.

참조한 코드의 링크를 첨부합니다.
https://sangdo913.tistory.com/8

**Comment by Scaachan** [comment]
같은 원리입니다.

4, 1, 9, 3, 2번 스위치 누르고 난 뒤의 `시계 - 스위치` 관계도는 아래와 같을 것입니다.

clock | switch
------|------
0 | 0, 5
1 | 0, 8
2 | 0, 5, 8
3 | 6, 8
4 | 7, 8
5 | 7, 8
7 | 7
14 | 5, 6, 7
15 | 5, 6, 7

뭔가 7번 스위치가 눌러달라고 하는 것 같지 않나요?😊 7번 시계가 유일히 7번 스위치와 연결되어 있으니

7번 시계가 필요한 만큼 7번 스위치를 누르고 나면 다음과 같습니다.

clock | switch
------|------
0 | 0, 5
1 | 0, 8
2 | 0, 5, 8
3 | 6, 8
4 | 8
5 | 8
14 | 5, 6
15 | 5, 6

이젠 8번 스위치가 눌러달라는 것 같네요.. 근데 4번과 5번 시계가 똑같이 8번에만 연결되어 있으므로

이 상태에서 4번과 5번 시계의 방향이 동일한지 조건문으로 우선 검사를 해주셔야 합니다.

방향이 동일하다면 4번이나 5번 둘 중 하나가 필요한 만큼 8번 스위치를 눌러줍니다.

clock | switch
------|------
0 | 0, 5
1 | 0
2 | 0, 5
3 | 6
14 | 5, 6
15 | 5, 6

그 후엔 0번 또는 6번 스위치가 눈에 띄는데, 저는 0번부터 눌렀습니다.

조건만 맞으면 스위치 누르는 순서는 상관 없습니다.

clock | switch
------|------
0 | 5
2 | 5
3 | 6
14 | 5, 6
15 | 5, 6

0번과 2번의 시계가 같은 5번 스위치를 공유하고 있으니 서로 방향이 같은지 확인해주시고, 같다면 5번 스위치를 누릅니다.

좀 전과 같이, 조건만 맞다면 순서는 상관없으니 6번 먼저 누르셔도 되는데

코드가 제일 군더더기 없어 보이는건 5번부터 누르는 것입니다.

clock | switch
------|------
3 | 6
14 | 6
15 | 6

마지막으로 3, 14, 15번 시계만 남았으니 이들의 방향이 모두 같은지 검사해주시고, 같다면 6번 눌러주시면 됩니다.

따라서 최종적으로 스위치 누르는 순서는 4 -> 1 -> 9 -> 3 -> 2 -> 7 -> 8 -> 0 -> 5 -> 6 가 됩니다.
