### ISSUE TITLE
[Week 1] BOGGLE debug review - hanjuuuuuu

### ISSUE THREAD

**Issue by Scaachan** [Scaachan/Advanced-Algorithm-Study#53]
***
- Related to :  #16
***
@hanjuuuuuu 님 BOGGLE 코드 디버깅 해드렸습니다.

수정은 최대한 원본을 해치지 않는 쪽으로 했습니다.

하단의 코드 변경 사항 확인하시고 TLE 사유 간단히 정리해서 PR 남겨주세요 :)

https://www.diffchecker.com/BwQVp8ut

**Comment by hanjuuuuuu** [comment]
네 확인했습니다~ 감사합니다!
