### ISSUE TITLE
[Week 1] BOGGLE debug review - yujungee

### ISSUE THREAD

**Issue by Scaachan** [Scaachan/Advanced-Algorithm-Study#72]
***
- Related to :  #11
***
@yujungee 님의 BOGGLE 코드는 거의 완성되어 있었고, 다음의 세 가지를 수정해드렸습니다.
1. 단어 배열 2개 혼용 -> `word` 배열을 지우고 대신 `words` 사용
2. 테스트케이스 돌리는 loop가 없음 -> `while(c--) { ... }` 로 한번 감쌌습니다.
3. 시간초과 -> 메모이제이션 적용

diffcheck 확인하시고 PR 주세요😊 감사합니다.

https://www.diffchecker.com/5T7lfo4N

**Comment by yujungee** [comment]
확인했습니다! 빠른 시일 내로 PR하겠습니다~ 감사합니다😊
