### ISSUE TITLE
BOGGLE 풀이에 참고할 수 있는 백준 문제

### ISSUE THREAD

**Issue by mily072** [Scaachan/Advanced-Algorithm-Study#8]
배열의 인덱스를 증가시켜가며 위치이동을 하고, 재귀호출로 DFS를 이용하는 문제라고
생각을 했습니다.

저를 포함해서, BOGGLE 풀이에 어려움이 있으신 분들 참고를 위해 백준 DFS 문제
링크를 첨부하도록 하겠습니다.

https://www.acmicpc.net/problem/16964
https://www.acmicpc.net/problem/1260

**Comment by yujungee** [comment]
감사합니다!

**Comment by Scaachan** [comment]
좋은 정보 감사합니다 :)

다만 참고로, BOGGLE은 dfs 만으로 AC를 받을 수 없습니다.

dfs에 한가지 테크닉을 더 적용하셔야 합니다.

그게 무엇인지는 #14 에 적어두었으니 필요하신 분들께선 참고바랍니다.
